Feature/dashboard
Senom-Dot/adm-dashboard pull request #6
Opened 2021-11-18 00:31 UTC by Al3xsandro

2021-11-18 10:28 UTC, NKKFu requested changes

2021-11-18 10:28 UTC, NKKFu commented on src/pages/error/index.js
> +                <Link to="/" style={{ textDecoration: 'none' }}>
Por que não colocar esse style dentro do Container?

2021-11-18 10:28 UTC, NKKFu commented on src/pages/dashboard/index.js
> +    setTimeout(() => {
Não é necessário simular essa request..

2021-11-18 10:28 UTC, NKKFu commented on src/pages/users/index.js
> +    setTimeout(() => {
Não é necessário simular essa request..

2021-11-18 10:28 UTC, NKKFu commented on src/pages/users/index.js
> +                            <HashLoader color="ABB69F" className="loading" size="100px"/>
Propriedade color sem hashtag? Estanho hein :P

2021-11-18 10:43 UTC, Al3xsandro commented on src/pages/error/index.js
> +                <Link to="/" style={{ textDecoration: 'none' }}>
Não pensei direito, corrigi aqui.
https://github.com/Senom-Dot/adm-dashboard/commit/2a36bd11893332b2fde5732f798352f97d9d9cc5

2021-11-18 10:44 UTC, Al3xsandro commented on src/pages/dashboard/index.js
> +    setTimeout(() => {
Certo.
https://github.com/Senom-Dot/adm-dashboard/commit/2a36bd11893332b2fde5732f798352f97d9d9cc5

2021-11-18 10:44 UTC, Al3xsandro commented on src/pages/users/index.js
> +    setTimeout(() => {
Certo.
https://github.com/Senom-Dot/adm-dashboard/commit/2a36bd11893332b2fde5732f798352f97d9d9cc5

2021-11-18 10:45 UTC, Al3xsandro commented on src/pages/users/index.js
> +                            <HashLoader color="ABB69F" className="loading" size="100px"/>
O React fez a correção e não pude perceber que não defini o hex corretamente.

2021-11-18 12:42 UTC, Al3xsandro commented
> Ainda definindo style invés de usar Container
Mostrei o porque de eu ter feito isso lá no slack, quando tiver tempo me diz se posso manter.

2021-11-25 01:25 UTC, NKKFu approved these changes

2021-11-25 01:25 UTC, merged